CREATE DATABASE banking_360;
USE banking_360;

SHOW TABLES;

## DATA VALIDATION:
SELECT COUNT(*) AS customer_count FROM customers;
SELECT COUNT(*) AS account_count FROM accounts;
SELECT COUNT(*) AS branch_count FROM branches;
SELECT COUNT(*) AS card_count FROM cards;
SELECT COUNT(*) AS loan_count FROM loans;
SELECT COUNT(*) AS loan_payment_count FROM loan_payments;
SELECT COUNT(*) AS transaction_count FROM transactions;
SELECT COUNT(*) AS complaint_count FROM complaints;
SELECT COUNT(*) AS service_request_count FROM service_requests;
SELECT COUNT(*) AS DATE_count FROM Date;

## Duplicate check 
SELECT CUSTOMER_ID, COUNT(*) AS duplicate_count
FROM customers
GROUP BY CUSTOMER_ID
HAVING COUNT(*)>1;

SELECT ACCOUNT_ID, COUNT(*) AS DUPLICATE_COUNT
FROM ACCOUNTS
GROUP BY ACCOUNT_ID
HAVING COUNT(*)>1;

SELECT BRANCH_ID, COUNT(*) AS DUPLICATE_COUNT
FROM BRANCHES
GROUP BY BRANCH_ID
HAVING COUNT(*)>1;

SELECT TRANSACTION_ID, COUNT(*) AS DUPLICATE_COUNT
FROM TRANSACTIONS
GROUP BY TRANSACTION_ID
HAVING COUNT(*)>1;

SELECT CARD_ID, COUNT(*) AS DUPLICATE_COUNT
FROM CARDS
GROUP BY CARD_ID 
HAVING COUNT(*)>1;

SELECT LOAN_ID, COUNT(*) AS DUPLICATE_COUNT
FROM LOANS
GROUP BY LOAN_ID
HAVING COUNT(*)>1;

SELECT COMPLAINT_ID, COUNT(*) AS DUPLICATE_COUNT
FROM COMPLAINTS
GROUP BY COMPLAINT_ID
HAVING COUNT(*)>1;

SELECT REQUEST_ID, COUNT(*) AS DUPLICATE_COUNT
FROM SERVICE_REQUESTS
GROUP BY REQUEST_ID  
HAVING COUNT(*)>1;

SELECT PAYMENT_ID, COUNT(*) AS DUPLICATE_COUNT
FROM LOAN_PAYMENTS
GROUP BY PAYMENT_ID  
HAVING COUNT(*)>1;

##### MISSING/NULL VALUES CHECK 
DESCRIBE CUSTOMERS;
SELECT COUNT(*) FROM CUSTOMERS WHERE CUSTOMER_ID IS NULL;
DESCRIBE ACCOUNTS;
SELECT COUNT(*) FROM ACCOUNTS WHERE ACCOUNT_ID IS NULL;
DESCRIBE BRANCHES;
SELECT COUNT(*) FROM BRANCHES WHERE BRANCH_ID IS NULL;
DESCRIBE CARDS;
SELECT COUNT(*) FROM CARDS WHERE CARD_ID IS NULL;
DESCRIBE COMPLAINTS;
SELECT COUNT(*) FROM COMPLAINTS WHERE COMPLAINT_ID IS NULL;
DESCRIBE LOANS;
SELECT COUNT(*) FROM LOANS WHERE LOAN_ID IS NULL;
DESCRIBE SERVICE_REQUESTS;
SELECT COUNT(*) FROM SERVICE_REQUESTS WHERE REQUEST_ID IS NULL;
DESCRIBE LOAN_PAYMENTS;
SELECT COUNT(*) FROM LOAN_PAYMENTS WHERE PAYMENT_ID IS NULL;
DESCRIBE TRANSACTIONS;
SELECT COUNT(*) FROM TRANSACTIONS WHERE TRANSACTION_ID IS NULL;

### CHECK NEGATIVE OR ZERO FINANCIAL VALUES
SELECT * FROM TRANSACTIONS WHERE AMOUNT<0;
SELECT * FROM LOANS WHERE LOAN_AMOUNT<=0;
SELECT * FROM LOANS WHERE INTEREST_RATE<0;

SELECT DISTINCT ACCOUNT_STATUS FROM ACCOUNTS;
SELECT DISTINCT TRANSACTION_TYPE FROM TRANSACTIONS;
SELECT DISTINCT LOAN_STATUS FROM LOANS;
SELECT DISTINCT STATUS FROM COMPLAINTS;
SELECT DISTINCT STATUS FROM SERVICE_REQUESTS;

SELECT * FROM COMPLAINTS 
WHERE RESOLVED_DATE < CREATED_DATE
AND STATUS = 'PENDING';

SELECT A.CUSTOMER_ID
FROM ACCOUNTS A 
LEFT JOIN CUSTOMERS C  
ON A.CUSTOMER_ID = C.CUSTOMER_ID 
WHERE C.CUSTOMER_ID IS NULL;

SELECT LP.LOAN_ID FROM LOAN_PAYMENTS LP
LEFT JOIN LOANS L  
ON LP.LOAN_ID =LP.LOAN_ID
WHERE L.LOAN_ID IS NULL;

############## EDA 
# CUSTOMER & ACCOUNTS ANALYSIS 
## TOTAL CUSTOMERS:
SELECT COUNT(*) AS TOTAL_CUSTOMERS FROM CUSTOMERS;
##TOTAL ACCOUNTS:
SELECT COUNT(*) AS TOTAL_ACCOUNTS FROM ACCOUNTS;
# ACTIVE ACCOUNTS:
SELECT ACCOUNT_STATUS,
	   COUNT(*) AS TOTAL_ACCOUNTS
FROM ACCOUNTS 
GROUP BY ACCOUNT_STATUS
ORDER BY TOTAL_ACCOUNTS;

## ACCOUNT-TYPE DISTRIBUTION;
SELECT ACCOUNT_TYPE,
	   COUNT(*)AS TOTAL_ACCOUNTS
FROM ACCOUNTS
GROUP BY ACCOUNT_TYPE
ORDER BY TOTAL_ACCOUNTS;

#CUSTOMER DISTRIBUTION:
SELECT GENDER, 
	   COUNT(*) AS TOTAL_CUSTOMERS
FROM CUSTOMERS 
GROUP BY GENDER;

## GEOGRAPHIC DISTRIBUTION:
SELECT STATE, 
	   CITY,
       COUNT(*) AS TOTAL_CUSTOMERS 
FROM CUSTOMERS 
GROUP BY STATE,
		 CITY;
         
### CUSTOMERS WITH MULTIPLE ACCOUNTS.
SELECT C.CUSTOMER_ID,
       C.CUSTOMER_NAME,
       COUNT(A.ACCOUNT_ID) AS TOTAL_NUM_ACCOUNTS
FROM CUSTOMERS C  
LEFT JOIN ACCOUNTS A 
ON C.CUSTOMER_ID = A.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
ORDER BY TOTAL_NUM_ACCOUNTS DESC
;

## TOTAL NUBMER OF TRANSACTIONS:
SELECT COUNT(*) AS TOTAL_TRANSACTIONS FROM TRANSACTIONS;

#TOTAL TRANSACTION AMOUT/value & AVG AMOUNT/VALUE:
SELECT ROUND(SUM(AMOUNT)) AS TOTAL_TRANSACTION FROM TRANSACTIONS;
SELECT ROUND(AVG(AMOUNT),2) AS AVERAGE_TRANSACTION_VALUE FROM TRANSACTIONS;

## TOTAL TRANSACTION VALUE BY TRANSACTION
SELECT TRANSACTION_TYPE, 
	   SUM(AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTIONS 
GROUP BY TRANSACTION_TYPE;

## NUM OF TRANSACTIONS BY TRANSACTION TYPE
SELECT TRANSACTION_TYPE, 
	   COUNT(TRANSACTION_ID) AS TOTAL_NUM_TRANSACTIONS
FROM TRANSACTIONS 
GROUP BY TRANSACTION_TYPE;

##MONTLY TRANSACTION TREND
SELECT MONTH(TRANSACTION_DATE) AS MONTH, 
        COUNT(*) AS TOTAL_TRANSACTIONS
FROM TRANSACTIONS
GROUP BY MONTH(TRANSACTION_DATE)
ORDER BY TOTAL_TRANSACTIONS DESC;

## TOP 10 CUSOTMERS/ACCOUNTS BY TRANSACTION 

## TRANSACTION ANALYSIS BY CHANNEL
SELECT CHANNEL, 
       COUNT(TRANSACTION_ID)AS TOTAL_COUNT,
       SUM(AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTIONS
GROUP BY CHANNEL;

## HIGH VALUE TRANSACTIONS
SELECT MAX(AMOUNT) AS HIGHEST_TRANSACTION FROM TRANSACTIONS;

## HIGHEST AND LOWEST TRANSACTION AMOUNT:
SELECT MAX(AMOUNT) AS HIGHEST_TRANSACTION,
       MIN(AMOUNT) AS LOWEST_TRANSACTION  
FROM TRANSACTIONS;


